### ISSUE TITLE
Where do we track "date last contacted"?

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#25]
Right now, we have it set up such that "date last contacted" is a manual field that we enter for both a project and a person.

Mostly I figured "okay, let's just set that up first and figure out the best way of doing it later", so we can leave it as-is for now, but at some point, we'll probably only want to track the "last-contacted" date for either a _person_ or for a _project_. Ideally, at some point in time, we'll be able to hook into the Zendesk/Github API to magically figure out when we last contacted someone—no manual data entry required—but that's probably a v3 feature.

It's likely worth discussing this now, so we can figure out a sensible way of approaching it. I'm leaning toward thinking it should be attached to the person (and then we can figure out when a "project" was last contacted by checking when we last spoke with anyone attached to the project), but that may not cover all our use cases.

Thoughts?

**Comment by michiecat** [comment]
I think "date last contacted" would be easier track by project than by person -- especially launched projects that no longer involve active communication. When we do our weekly checkins during Maintenance Week, it's easier to scan the list of launched projects and see the date we last communicated with someone about that project. When we write the checkin emails, it's the project that we're inquiring about. Clicking on a specific project would show the people who are associated with it -- it's easier to see who to contact. If we do it by person then it's more difficult to manage because we'll have more people than projects.

For active projects (or projects that have launched but involve frequent communication), the "Date last contacted" field can be "ongoing". 

For projects that have launched but are quiet, "date last contacted" can have a specific date. I think this should always be a manual field that we control.

**Comment by sarahmonster** [comment]
"Date last contacted" is really tricky since it's reasonably important, but it's a pain to update. Ideally, we'll be able to (eventually) automate a lot of this work by using the Zendesk & Github APIs, although that will definitely be a v3 feature. 

In terms of accessing the data from Github/Zendesk in the future, Github makes it easier to associate the contact date with a project, and Zendesk makes it easier to associate it with a person. We also have a mystery third option, which would be to attach this to an organisation, but I think that's likely the worst of all options. 

Ideally whichever way we go, we'll still be able to show a "date last contacted" field for both a person and a project by searching their attached CPT. (ie, if we attach dates to projects, we can show the date a person was last contacted by searching for projects they're attached to, and grabbing the associated date there.)

Since we contact people rather than projects, I wonder if that's the more sensible association, particularly when we have certain people who are attached to multiple projects. However, we do tend to associate a check-in to a particular project, so that might be the more sensible option. I think either solution has drawbacks and I'm not sure the best approach here. 

> When we do our weekly checkins during Maintenance Week, it's easier to scan the list of launched projects and see the date we last communicated with someone about that project. 

Ideally this won't be a thing we do at all—we should just be able to look at the dashboard and see which clients require a check-in. (See #35.) Manually scanning a list is something I'd super like to avoid, and it won't scale as we launch more sites. 

> For projects that have launched but are quiet, "date last contacted" can have a specific date. I think this should always be a manual field that we control. 

Free-form text entry will make it super difficult to programmatically access the data, but I can understand the need for an "ongoing communication" field. (We'll just need to be sure we update this once we stop communicating with someone.)

Offhand, I can think of two ways of approaching this:
- Adding an additional project status for "launched with ongoing communication". Only "launched" projects will be scanned for client check-ins.
- Building a custom UI component to basically allow for entering either a date (using a datepicker so it's entered in a standardised & programmatically-accessible format) or an "ongoing communication" option for the "date last contacted" field. This would keep the data all consistent so we've be able to use it programmatically, and we could just filter out the "ongoing communication" dates from the front-end. 

So I think there could potentially be a few things to consider here from a data perspective and may warrant further discussion before we move on to v2.

**Comment by sarahmonster** [comment]
On further thought, it may actually make sense to attach "date last contacted" to a *person*, but attach the check-ins to a *project*. This approach may require a bit more custom-coding to make those associations work properly, but it's effectively in line with how we approach check-ins—we contact people, but the check-ins are tied to a project.

Alternately, maybe it *does* make sense to attach the dates to both people and projects, but abstract them a little: "date last contacted" is for a person (and will ultimately be attached to Github/Zendesk data) and "last check-in" is associated with a project.

**Comment by michiecat** [comment]
What would be the benefit of a date last contacted for a person? Is there a value in it? What would we use it for? I'm asking because I'm not even sure if it's necessary for v1. If we want date-last-contacted for people, it should be a v2 or v3 feature and something that gets pulled in via Zendesk.

I can see the value of checkin dates for projects, because that's the most important thing we're following up with. I worry that a date-last-contacted for people might be redundant or something we won't make much use of. My vote is to consider removing it for v1, and just use checkins for projects. If we see a need for date last contacted for people, we can add it in v2. What do you think? 

We came to the same conclusion independently about using project statuses for the "ongoing communication" field. Yay! See my comments in #35. :) I'll quote the relevant bits here for reference: 

>My SUPER STRONG vote is for checkins to be associated with projects. That's how we do it currently and it's most straightforward. We'll naturally have fewer projects than people, since multiple people can be associated with one project. We'll be able to see which people to contact by viewing the project when it's next up in the list for checking in. It also makes sense to associate checkins with projects because that's what we're inquiring about -- their website.

and 

>For launched projects that we want to exclude from checkins, we could utilize the project status field, and avoid making new fields or settings to fill out. For example, we could have "Launched - Active" or "Launched - [Some Other Condition]".

>Ideally this won't be a thing we do at all—we should just be able to look at the dashboard and see which clients require a check-in. (See #35.) Manually scanning a list is something I'd super like to avoid, and it won't scale as we launch more sites.

Yes, what you have in your sketch in #35, scanning a list of projects for checkins was what I was thinking all along, but my wording wasn't very clear. :) Instead of scanning a spreadsheet like we do now, we're scanning a list of upcoming projects due for a checkin. I have more comments on that in #35.

**Comment by michiecat** [comment]
>What would be the benefit of a date last contacted for a person? Is there a value in it? What would we use it for? I'm asking because I'm not even sure if it's necessary for v1. Every person is associated with a project, and there will be a last check-in date for every project. As our number of clients grow, I can't see us tracking last-contact-dates for each individual person as well.

Answering my own questions. Last-contacted-date for a client could be useful for:

* Active projects -- when did we last hear from them (especially if it's tied to Github/Zendesk). We'd use this data to determine if a project has gone cold. BUT even so, if we're actively working on a project we can tell if clients stop communicating and things have gone cold. Entering that data in strikebase seems redundant.
* Helps other team members who join a project get a sense of when we last communicated with a client. 
* Helps us sort out clients who are no longer associated with a project. 

I still vote for punting "date last contacted" to v2 for people (when we can pull in those dates automatically via an API), and just have "last checkin date" for projects for v1. Let's keep it as simple as possible for v1.

**Comment by michiecat** [comment]
Alternatively, we could list the last checkin dates for each project a person is associated with. The checkin date itself is associated with the project and is thus updated on the project itself.

**Comment by sarahmonster** [comment]
I'd agree with removing the "date last contacted" field for a person (for now!) and re-adding it later. I'd also like to change the "date last contacted" field attached to a project to a "date of last check-in" field, so it's more clear what that means. 

Since a project check-in may not necessarily contact *all* people attached to that project, I do think it could make sense to re-implement this field (using Zendesk API) at v3, but for our current needs, I think we should just remove the date-contacted fields from people entirely—we don't really need them right now and they don't provide enough value. Once we're further along, we may be able to use them to calculate check-in dates etc based on Zendesk communications, but for now, I'd vote for simplifying and only using a check-in date attached to a project.
