### ISSUE TITLE
Show check-ins on dashboard

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#35]
My original wireframes (#1) for the dashboard are intended for it to be a collected place where we can see all the items that require our immediate attention: outstanding Zendesk tickets, Github issues, etc. 

Something like this:

![img_0592](https://cloud.githubusercontent.com/assets/376315/18953698/8ecfa8ac-8647-11e6-8064-7c0fd1c8145f.jpg)

I think anything requiring an integration with an API (Github, Zendesk, Twitter) should really be pushed to v3, but the other elements we can tackle for v2. 

The most important bit would be the check-in notifications. I'm thinking this would just show a list of upcoming check-ins based on a given date interval. For the date interval, we may want to have a default interval that could then be overridden for certain projects as needed. 

We'll need to figure out our rules for check-ins first, mostly in terms of should they be associated with projects, people, or organisations? (See #25 for further discussion.)

The list would basically display the next upcoming client check-ins with their scheduled date, and a little red arrow/warning icon to indicate late check-ins. This allows us to easily see who's due for a check-in without needing to look up every client or project in the database.

**Comment by michiecat** [comment]
My SUPER STRONG vote is for checkins to be associated with projects. That's how we do it currently and it's most straightforward. We'll naturally have fewer projects than people, since multiple people can be associated with one project. We'll be able to see which people to contact by viewing the project when it's next up in the list for checking in. It also makes sense to associate checkins with projects because that's what we're inquiring about -- their website. 

> The most important bit would be the check-in notifications. I'm thinking this would just show a list of upcoming check-ins based on a given date interval. For the date interval, we may want to have a default interval that could then be overridden for certain projects as needed.

If FieldManager's date field lets us sort by date, we could do a query to list all projects with a status of "launched" (again, strong vote for associating checkins with projects!!) by date, in order of least-recent to most-recent. The 3 least-recent would appear appear in the "Checkins" list on your sketch.  When someone checks in, they update the checkin date, and the project moves to the bottom of the list. We'd exclude projects that have a status other than "launched". 

For launched projects that we want to exclude from checkins, we could utilize the project status field, and avoid making new fields or settings to fill out. For example, we could have "Launched - Active" or "Launched - [Some Other Condition]".

**Comment by michiecat** [comment]
For v3 it'd be cool to add a stats page to help us track statistics (see #39). 

How are you envisioning the "red alert" to work? I was originally proposing listing checkins by date, with least-recent first. But if we want to do an alerts system, we'd need to do the intervals system you suggested. Can you explain how that would work? :)

**Comment by sarahmonster** [comment]
> How are you envisioning the "red alert" to work? I was originally proposing listing checkins by date, with least-recent first. But if we want to do an alerts system, we may need to do the intervals system that you suggested. Can you explain how that would work? :)

I think we'd need to use an interval system, because some clients require more-frequent check-ins than others. This would basically just allow us to fine-tune the default behaviour where necessary. 

Basically we'd set a default interval (every six months) and each project would also have a custom field for "check-in interval" that would accept a number (of months, I think?). Any projects without a custom check-in interval field would use the default interval.

This way, each check-in would have a scheduled date, calculated by adding the interval to the date of the last check-in. The dashboard widget would show upcoming check-ins, with the scheduled date of that check in, in chronological order. Late check-ins (ie, check-ins with a scheduled date after today's date) would show in red, with a little alert icon. 

Right now, we're doing a "one a week" system, which works—but this approach allows us more fine-grained control of when check-ins happen, and works better in the long run, since we'll be doing the check-ins at regular intervals, rather than whenever someone shows up on our list.

**Comment by michiecat** [comment]
I think number of months makes sense, with 6 months being a good default. However as the number of projects grows, we might need to adjust the default interval. But to start with I'd say 6 months as default.

**Comment by sarahmonster** [comment]
We can aim to set this up so it's easy to adjust—maybe a theme option or some-such.
