### ISSUE TITLE
How do we handle suggested/queued-up projects?

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/strikebase#40]
This just occurred to me now. How do we handle suggested projects, or projects that are set to start but haven't yet started? 

I guess it'd be easiest to utilize project status: "accepted-unassigned", "accepted-punted", "accepted-in-queue", or "new-non-triaged" (we have to decide on the best statuses).

Because we like to keep track of who suggested a project, we should have a field in projects where we enter the suggester's name (if we already have one, disregard). 

To aid in finding these projects, they should be listed somewhere. Maybe a page template that lists all projects by the statuses listed above?

**Comment by sarahmonster** [comment]
Statuses are pretty flexible, because they're a taxonomy—so we can add/adjust/rename them directly from wp-admin. We can change them as needed once we get a sense of which ones we'd need.

> Because we like to keep track of who suggested a project, we should have a field in projects where we enter the suggester's name (if we already have one, disregard).

There's a field for "referrer" already!

> To aid in finding these projects, they should be listed somewhere. Maybe a page template that lists all projects by the statuses listed above?

Wireframes accounted for a "sort" filter on the project listing page—right now it just lists out the statuses, but you can't sort them. Filed this as #41!

**Comment by michiecat** [comment]
OK. Then for v1 we can just use the static archive pages for the taxonomies if we want to view projects by status.

**Comment by sarahmonster** [comment]
You can view a taxonomy page from here, but they're missing a template: http://strikebase.dev/project-status/launched/

I can create a template and link them from the main projects page if this would be helpful here?
