### ISSUE TITLE
Project statuses: "launched" v.  "complete"

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#72]
I just noticed that we have two different project statuses that seem to be synonyms: launched and complete. What's the difference between these?

**Comment by michiecat** [comment]
This is not a bug, but intentional.

"Launched" - New site/theme launched.

"Complete" - Question answered or issue resolved (but no launch is involved).

We started using those two terms back in 2014 when we first started tracking strikes, and I've found it useful as a way of distinguishing the two.

**Comment by sarahmonster** [comment]
Ah—I didn't know that was a convention we used. I'm not opposed to it per se now that I know the rationale, but I wonder if it could potentially be confusing for others as well. Does the status dictate how we approach the site in the future in terms of maintenance? Is this difference already communicated by the project type itself?

Since this is a content issue rather than a structure issue, it can easily be tweaked at a later stage. This may be worth an internal discussion at some point, but I don't think it's important right now.
