### ISSUE TITLE
Design component: project listing

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#79]
Should show title, status, launch date (or expected launch date), and date of last check-in.

Is there any other important information to show here? Maybe if we already have upcoming check-ins on the dashboard (#59) we don't need to highlight that information here anymore. Perhaps genre or project type or host would be more useful?

Also consider using icons and/or colour-coding here to differentiate different types of projects. Maybe we could use icons #74 to display host, genre, and project type in a very small space.

![project list](https://cloud.githubusercontent.com/assets/376315/22654339/606369d8-ec84-11e6-9858-33757145c3e0.png)

Should be coded into style guide as HTML/CSS.

**Comment by michiecat** [comment]
Because Genre and Project type are offered as filters, I think we should show those two, at least. Hosting would also be useful.

I'm torn on whether we should show the check-in date here. It's useful to have it available at a glance without needing to go to the single view. At the same time, the Dashboard will show which projects are up for a check-in so it could be redundant here. ¯\_(ツ)_/¯ What if we remove the check-in date and see how it feels? We can add it back later if it's needed.

I like the idea of using icons for some of this info, especially for hosting.

**Comment by sarahmonster** [comment]
I've removed the check-in date here since I don't think it's super-useful—I'd like to keep things super-simple and only add things as we determine there's a need to be met. 

Icons will be added as part of #74.

**Comment by michiecat** [comment]
Sounds good!
